### ISSUE TITLE
xtreemfs docker not working

### ISSUE THREAD

**Issue by fedya** [xtreemfs/xtreemfs-docker#3]
i run 

docker run -v /xtreemfs_data:/xtreemfs_data -p 32640:32640 -t -d xtreemfs/xtreemfs-osd:latest
docker run -v /xtreemfs_data:/xtreemfs_data -p 32638:32638 -t -d xtreemfs/xtreemfs-dir:latest
docker run -v /xtreemfs_data:/xtreemfs_data -p 32636:32636 -t -d xtreemfs/xtreemfs-mrc:latest

And i got 
MRC
https://gist.github.com/fedya/d5319a1e683f7b87c4b5
OSD
https://gist.github.com/fedya/934030f64bb42a7ceae0

DIR is working
https://gist.github.com/fedya/955b926d4ade4677944a

**Comment by chrkl** [comment]
Did you point to the correct DIR host in your MRC and OSD config?

**Comment by fedya** [comment]
Well now i'm able to start dockerized xtreemfs.
i just replaced 
dir_service.host = 
with DIR-service container name
dir_service.host = dirservice_container

Well if dir, mrc ,osd services is working what next?
Official readme says that i need to run 
docker run -t -i --privileged xtreemfs/xtreemfs-client /bin/bash

but what next step?

**Comment by chrkl** [comment]
I recommend to have a look at the XtreemFS user guide (http://xtreemfs.org/xtfs-guide-1.5.1/index.html) and the quick start guide (http://xtreemfs.org/quickstart.php). If your services are running, creating and mounting a volume would be the next step.
The README just describes how to get the containers running and is not a general introduction to XtreemFS.

**Comment by fedya** [comment]
yes, i'm following guide.

root@8136c3106771:~# lsfs.xtreemfs servername:32636
Listing all volumes of the MRC: 46.105.121.20:32636
Volumes on servername:32636 (Format: volume name -> volume UUID):
        file-store      ->      250f16e3-1b29-4657-9e72-c39212455db9
End of List.

Trying to mount

mount.xtreemfs servername/file-store ~/xtreemfs

[ E | 10/31 14:41:14.341 | 7fbcb61a3700   ] operation failed: call_id=1 errno=5 message=could not connect to host '172.17.0.62:32636': No route to host 
[ E | 10/31 14:41:14.341 | 7fbcba4fe780   ] Got no response from server 172.17.0.62:32636 (default-MRC), retrying (infinite attempts left) (Possible reason: The server is using SSL, and the client is not.), waiting 12.0 more seconds till next attempt.

**Comment by chrkl** [comment]
The 172.x.x.x IP address seems to be part of the internal docker network. You have to configure the hostname parameter for your MRC and OSD services. This is the address, which is used to register at the DIR service. As the services in a container are not aware of their public address (the address of the host), you have to set this parameter on your own.

**Comment by fedya** [comment]
/xtreemfs_data/mrcconfig.properties 
dir_service.host = dirservice_container

/xtreemfs_data/osdconfig.properties
dir_service.host = dirservice_container

but i still see

root@6f19e58293e8:/# mount.xtreemfs 46.105.121.20/file-store ~/xtreemfs
[ E | 10/31 15:07:41.393 | 7fbac9426700   ] operation failed: call_id=1 errno=5 message=could not connect to host '172.17.0.62:32636': No route to host 
[ E | 10/31 15:07:41.393 | 7fbacd781780   ] Got no response from server 172.17.0.62:32636 (default-MRC), retrying (infinite attempts left) (Possible reason: The server is using SSL, and the client is not.), waiting 12.0 more seconds till next attempt.

**Comment by chrkl** [comment]
As mentioned in my last post, the "hostname" parameter is missing. Please see section 3.2.1 and 3.2.2 of the user guide for details.

**Comment by fedya** [comment]
Working!

**Comment by chrkl** [comment]
Great!
