### ISSUE TITLE
Installation on architecture != amd64

### ISSUE THREAD

**Issue by jeanibarz** [xtreemfs/xtreemfs-docker#6]
https://github.com/xtreemfs/xtreemfs-docker/blob/178ede2c8d65b26697b4302fedd3ba13bb59db68/xtreemfs-common/Dockerfile#L15

When trying to install on a Raspberry Pi 3B+ (architecture armhf), the image building doesn't work because the JAVA path refers to a wrong path, corresponding to the amd64 architecture.

I wonder if it is possible to slightly the modify the Dockerfile to deduce the correct path from the running architecture or allow with any regex expression to find the correct path from a regex expression ? This would allow the building to succeed no matter architecture.

 Best regards

**Comment by robert-schmidtke** [comment]
Hi,

you could check whether there is a symlink called `/usr/lib/jvm/default-java` that points to the architecture-specific directory. If so, you can replace the paths accordingly in the Dockerfile, double-check with the amd64 Ubuntu image, and then open a PR.

Cheers
Robert

**Comment by mickenordin** [comment]
I have tried building these images for arm64 with podman buildx and it works (with debian:bookworm-slim as base image), so I think this can be closed.
